# The Site Configuration
# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: ko-KR

# Change to your timezone
timezone: Asia/Seoul

# jekyll-seo-tag settings
title: rd
tagline: 다시 보기 위한 정리
description: >-
  개발 기록과 생각 정리

# Fill with your site URL, e.g. 'https://username.github.io'
url: "https://thahiti.github.io"

github:
  username: thahiti

social:
  name: rd
  links:
    - https://github.com/thahiti

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID

# Prefer color scheme setting
# Options: light, dark, ""(follow system)
theme_mode: ""

# The CDN endpoint for media resources
# e.g. 'https://cdn.com'
cdn:

# the avatar on sidebar, support local or CORS resources
avatar:

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
social_preview_image:

# boolean type, the global switch for TOC in posts
toc: true

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: # [disqus | utterances | giscus]
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# Self-hosted static assets, optional
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _tabs
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: ""
    values:
      layout: default

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
